name: CI pipeline

on:
  push:
    branches: [ "main" ]  
  pull_request:          
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"  

      - name: Install Poetry
        run:  |
          cd aoot
          pip install poetry

      - name: Install dependencies
        run: |
          cd aoot
          poetry install 

      - name: Run tests
        run: |
          cd aoot
          poetry run pytest 